### ISSUE TITLE
credentials support

### ISSUE THREAD

**Issue by hmn** [hthiery/python-ps4#2]
I don't know if you plan to build registration into the module, but if not it would make sense to have the option to add the credentials json config directly instead of having to use the credentials file

It would be a bit easier to use it that way inside home assistant

**Comment by hthiery** [comment]
You mean the credential String instead of the File?

**Comment by hmn** [comment]
yes

but I guess the usage depends on how much of ps4-waker you plan to implement, because right now you basicly need to generate the credentials somewhere else and then tell home assistant about it

so if thats the initial plan then it would be much easier to just allow the user to add the json in the gui (or the config) as a credentials string
