### ISSUE TITLE
network connection does not work from docker

### ISSUE THREAD

**Issue by hthiery** [hthiery/python-ps4#9]
root@server:/# ps4-ctrl  -C <CREDENTIAL> wakeup
Traceback (most recent call last):
  File "/usr/local/bin/ps4-ctrl", line 11, in <module>
    load_entry_point('pyps4===0.1.4-6-g6f7d1ec', 'console_scripts', 'ps4-ctrl')()
  File "/usr/local/lib/python3.6/site-packages/pyps4-0.1.4_6_g6f7d1ec-py3.6.egg/pyps4/cli.py", line 154, in main
  File "/usr/local/lib/python3.6/site-packages/pyps4-0.1.4_6_g6f7d1ec-py3.6.egg/pyps4/cli.py", line 41, in cmd_wakeup
  File "/usr/local/lib/python3.6/site-packages/pyps4-0.1.4_6_g6f7d1ec-py3.6.egg/pyps4/ps4.py", line 79, in wakeup
  File "/usr/local/lib/python3.6/site-packages/pyps4-0.1.4_6_g6f7d1ec-py3.6.egg/pyps4/ddp.py", line 109, in wakeup
  File "/usr/local/lib/python3.6/site-packages/pyps4-0.1.4_6_g6f7d1ec-py3.6.egg/pyps4/ddp.py", line 85, in _send_msg
  File "/usr/local/lib/python3.6/site-packages/pyps4-0.1.4_6_g6f7d1ec-py3.6.egg/pyps4/ddp.py", line 77, in _send_recv_msg
TypeError: str, bytes or bytearray expected, not NoneType

**Comment by hmn** [comment]
as far as I know the credentials and host options are required, see the examples in the docker-run.sh command

at least it works here when I test it out here, and I get the same error if I don't set the right params

but of course it might make sense to handle it better

**Comment by hthiery** [comment]
ok ... that means the error only occures when not all required options are properly set.

in this example missing -H host options fails

**Comment by hmn** [comment]
no I think you are mixing things the python error is not docker related, the error you posted is because you did not set all options

it's the same error if you run the command locally from your machine

**Comment by hthiery** [comment]
currently for me it is not clear what the docker error is

**Comment by hmn** [comment]
run the wakeup on docker and your ps4 is not turning on it just ignores the packets

**Comment by hthiery** [comment]
hmm ... will try it again later .. but I think yesterday I was able to turn the PS4 with the wakeup from the docker.

**Comment by hthiery** [comment]
`docker run --rm --net=host -it 7ba8ede6ae56 -v -H 192.168.0.197 -C <CREDENTIAL> wakeup`
-> PS4 is turning on

`docker run --rm --net=host -it 7ba8ede6ae56 -v -H 192.168.0.197 -C <CREDENTIAL> status
{'device-discovery-protocol-version': '00020020',
 'host-id': 'F8461CE2701E',
 'host-ip': '192.168.0.197',
 'host-name': 'PS4',
 'host-request-port': '997',
 'host-type': 'PS4',
 'status': 'Ok',
 'status_code': 200,
 'system-version': '05508011'}`
-> PS4 status info

`docker run --rm --net=host -it 7ba8ede6ae56 -v -H 192.168.0.197 -C <CREDENTIAL> standby`
-> PS4 goes to standby

The toolset seems to work executed inside docker.

**Comment by hthiery** [comment]
I think there is another issue inside your environment. Do you use the right credential? I can remember an issue that I had when I used an credential that I generated on another machine.

**Comment by hmn** [comment]
the credentials work outside the box, but it's a bit complicated to generate the credentials on hass.io as I then need to get ps4-waker working there

i'll see if I can find a way to generate the key from the home assistant machine and get back to you

**Comment by hthiery** [comment]
Ist sounds we we have to get the credential via pyps4.

**Comment by hmn** [comment]
I got nodejs and ps4-waker installed and generated the credentials on the hassio machine and now it works

you are right each mac seem to be whitelisted on the ps4 when the registration process runs

so as you mention it would require that we get the registration process to work in the python module, as the install process would be way too complicated otherwise

**Comment by hthiery** [comment]
#4 enhancement is already opened. But I dont know if there is already any process and currently I dont  know when I find the time to start that by myself.
